---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: gb5
spec:
  selector:
    service: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
