---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kubedoom-deploy
  namespace: kubedoom
  labels:
    app   : my-kubedoom-application
    env   : prod
    owner : zzbike
spec:
  replicas: 1
  selector:
    matchLabels:
      project: gb-3-kubedoom
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        project: gb-3-kubedoom
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - image: storaxdev/kubedoom:0.5.0
        name: kubedoom
        ports:
        - containerPort: 5900
          protocol: TCP