---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc-nfs-01
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pg-pv-nfs-01
  storageClassName: ""
